<?php require_once __DIR__.'/../app/db.php'; require_once __DIR__.'/../app/layout.php'; require_login(); require_perm(can('clients')?'clients':'clients_view'); $pdo=pdo(); $edit=null;
if($_SERVER['REQUEST_METHOD']==='POST' && can('clients')){
 $fields=['type_client','nom','prenom','telephone','email','nationalite','cin','passport','date_expiration_cin','numero_permis','date_delivrance_permis','delivre_a_permis','date_naissance','lieu_naissance','adresse','adresse_etrangere','notes'];
 $vals=[]; foreach($fields as $f) $vals[$f]=post($f);
 if(post('id')){ $set=implode(',',array_map(fn($f)=>"$f=?",$fields)); $stmt=$pdo->prepare("UPDATE clients SET $set WHERE id=?"); $stmt->execute([...array_values($vals),post('id')]); flash('Client modifié avec succès.'); log_action('Modification client',post('nom').' '.post('prenom')); }
 else { $cols=implode(',',$fields); $qs=implode(',',array_fill(0,count($fields),'?')); $stmt=$pdo->prepare("INSERT INTO clients($cols) VALUES($qs)"); $stmt->execute(array_values($vals)); flash('Client ajouté avec succès.'); log_action('Ajout client',post('nom').' '.post('prenom')); }
 redirect('/clients.php');
}
if(getv('delete') && can('clients')){ $pdo->prepare('DELETE FROM clients WHERE id=?')->execute([getv('delete')]); flash('Client supprimé.'); redirect('/clients.php'); }
if(getv('edit')){ $stmt=$pdo->prepare('SELECT * FROM clients WHERE id=?'); $stmt->execute([getv('edit')]); $edit=$stmt->fetch(); }
$q=trim(getv('q','')); if($q){$stmt=$pdo->prepare("SELECT * FROM clients WHERE nom LIKE ? OR prenom LIKE ? OR telephone LIKE ? OR cin LIKE ? OR passport LIKE ? ORDER BY id DESC"); $like="%$q%"; $stmt->execute([$like,$like,$like,$like,$like]); $rows=$stmt->fetchAll();} else $rows=$pdo->query('SELECT * FROM clients ORDER BY id DESC')->fetchAll();
render_header('Gestion des clients'); ?>
<section class="panel"><div class="panel-head"><h2>Clients</h2><?php if(can('clients')):?><a class="btn primary" href="/clients.php?action=new">+ Ajouter client</a><?php endif;?></div><form class="search"><input name="q" placeholder="Recherche par nom, téléphone, CIN, passeport..." value="<?=e($q)?>"><button class="btn">Rechercher</button></form>
<?php if((getv('action')==='new'||$edit) && can('clients')): $c=$edit??[]; ?><form method="post" class="form-grid"><input type="hidden" name="id" value="<?=e($c['id']??'')?>"><label>Type<select name="type_client"><option>Marocain</option><option <?=($c['type_client']??'')==='Etranger'?'selected':''?>>Etranger</option><option <?=($c['type_client']??'')==='Entreprise'?'selected':''?>>Entreprise</option></select></label><label>Nom<input name="nom" required value="<?=e($c['nom']??'') ?>"></label><label>Prénom<input name="prenom" value="<?=e($c['prenom']??'') ?>"></label><label>Téléphone<input name="telephone" value="<?=e($c['telephone']??'') ?>"></label><label>Email<input name="email" value="<?=e($c['email']??'') ?>"></label><label>Nationalité<input name="nationalite" value="<?=e($c['nationalite']??'Marocaine') ?>"></label><label>CIN<input name="cin" value="<?=e($c['cin']??'') ?>"></label><label>Passeport<input name="passport" value="<?=e($c['passport']??'') ?>"></label><label>Expiration CIN<input type="date" name="date_expiration_cin" value="<?=e($c['date_expiration_cin']??'') ?>"></label><label>N° permis<input name="numero_permis" value="<?=e($c['numero_permis']??'') ?>"></label><label>Délivrance permis<input type="date" name="date_delivrance_permis" value="<?=e($c['date_delivrance_permis']??'') ?>"></label><label>Délivré à<input name="delivre_a_permis" value="<?=e($c['delivre_a_permis']??'') ?>"></label><label>Date naissance<input type="date" name="date_naissance" value="<?=e($c['date_naissance']??'') ?>"></label><label>Lieu naissance<input name="lieu_naissance" value="<?=e($c['lieu_naissance']??'') ?>"></label><label class="span2">Adresse<textarea name="adresse"><?=e($c['adresse']??'') ?></textarea></label><label class="span2">Adresse étrangère<textarea name="adresse_etrangere"><?=e($c['adresse_etrangere']??'') ?></textarea></label><label class="span2">Notes<textarea name="notes"><?=e($c['notes']??'') ?></textarea></label><div class="form-actions span2"><button class="btn primary">Enregistrer</button><a class="btn" href="/clients.php">Annuler</a></div></form><?php endif; ?>
<div class="table-wrap"><table><thead><tr><th>Client</th><th>Contact</th><th>Identité</th><th>Permis</th><th>Actions</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><b><?=e($r['nom'].' '.$r['prenom'])?></b><small><?=e($r['type_client'].' · '.$r['nationalite'])?></small></td><td><?=e($r['telephone'])?><small><?=e($r['email'])?></small></td><td><?=e($r['cin'] ?: $r['passport'])?></td><td><?=e($r['numero_permis'])?></td><td class="actions"><a class="btn small" href="/profile.php?id=<?=$r['id']?>">Profil</a><?php if(can('clients')):?><a class="btn small" href="/clients.php?edit=<?=$r['id']?>">Modifier</a><a class="btn small danger" data-confirm="Supprimer ce client ?" href="/clients.php?delete=<?=$r['id']?>">Supprimer</a><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></section><?php render_footer(); ?>
