<?php require_once __DIR__.'/../app/db.php'; require_once __DIR__.'/../app/layout.php'; require_login(); require_perm(can('voitures')?'voitures':'voitures_view'); $pdo=pdo(); $edit=null;
if($_SERVER['REQUEST_METHOD']==='POST' && can('voitures')){
 $fields=['immatriculation','marque','modele','type_vehicule','carburant','puissance_fiscale','consommation','rejet_co2','date_immatriculation','date_acquisition','kilometrage_actuel','cout_jour','statut','date_dernier_controle','date_prochain_controle','cadence_vidange','km_derniere_vidange','cadence_courroie','km_derniere_courroie','assurance_expire_le','remarques']; $vals=[]; foreach($fields as $f)$vals[$f]=post($f);
 if(post('id')){$set=implode(',',array_map(fn($f)=>"$f=?",$fields));$stmt=$pdo->prepare("UPDATE voitures SET $set WHERE id=?");$stmt->execute([...array_values($vals),post('id')]);flash('Véhicule modifié.');} else {$cols=implode(',',$fields);$qs=implode(',',array_fill(0,count($fields),'?'));$stmt=$pdo->prepare("INSERT INTO voitures($cols) VALUES($qs)");$stmt->execute(array_values($vals));flash('Véhicule ajouté.');} redirect('/voitures.php');
}
if(getv('delete') && can('voitures')){$pdo->prepare('DELETE FROM voitures WHERE id=?')->execute([getv('delete')]);flash('Véhicule supprimé.');redirect('/voitures.php');}
if(getv('edit')){$stmt=$pdo->prepare('SELECT * FROM voitures WHERE id=?');$stmt->execute([getv('edit')]);$edit=$stmt->fetch();}
$q=trim(getv('q','')); if($q){$stmt=$pdo->prepare("SELECT * FROM voitures WHERE immatriculation LIKE ? OR marque LIKE ? OR modele LIKE ? ORDER BY id DESC");$like="%$q%";$stmt->execute([$like,$like,$like]);$rows=$stmt->fetchAll();} else $rows=$pdo->query('SELECT * FROM voitures ORDER BY id DESC')->fetchAll();
render_header('Gestion des véhicules'); ?>
<section class="panel"><div class="panel-head"><h2>Véhicules</h2><?php if(can('voitures')):?><a class="btn primary" href="/voitures.php?action=new">+ Ajouter véhicule</a><?php endif;?></div><form class="search"><input name="q" placeholder="Recherche par immatriculation, marque, modèle..." value="<?=e($q)?>"><button class="btn">Rechercher</button></form>
<?php if((getv('action')==='new'||$edit) && can('voitures')):$v=$edit??[]; ?><form method="post" class="form-grid"><input type="hidden" name="id" value="<?=e($v['id']??'')?>"><label>Immatriculation<input name="immatriculation" required value="<?=e($v['immatriculation']??'')?>"></label><label>Marque<input name="marque" required value="<?=e($v['marque']??'')?>"></label><label>Modèle<input name="modele" required value="<?=e($v['modele']??'')?>"></label><label>Type<input name="type_vehicule" value="<?=e($v['type_vehicule']??'')?>"></label><label>Carburant<input name="carburant" value="<?=e($v['carburant']??'')?>"></label><label>Puissance fiscale<input name="puissance_fiscale" value="<?=e($v['puissance_fiscale']??'')?>"></label><label>Consommation<input name="consommation" value="<?=e($v['consommation']??'')?>"></label><label>CO2<input name="rejet_co2" value="<?=e($v['rejet_co2']??'')?>"></label><label>Date immatriculation<input type="date" name="date_immatriculation" value="<?=e($v['date_immatriculation']??'')?>"></label><label>Date acquisition<input type="date" name="date_acquisition" value="<?=e($v['date_acquisition']??'')?>"></label><label>Kilométrage<input type="number" name="kilometrage_actuel" value="<?=e($v['kilometrage_actuel']??0)?>"></label><label>Prix/jour<input type="number" step="0.01" name="cout_jour" value="<?=e($v['cout_jour']??0)?>"></label><label>Statut<select name="statut"><?php foreach(['Disponible','Louée','Maintenance','Vendue'] as $s):?><option <?=$s===($v['statut']??'Disponible')?'selected':''?>><?=$s?></option><?php endforeach;?></select></label><label>Dernier contrôle<input type="date" name="date_dernier_controle" value="<?=e($v['date_dernier_controle']??'')?>"></label><label>Prochain contrôle<input type="date" name="date_prochain_controle" value="<?=e($v['date_prochain_controle']??'')?>"></label><label>Assurance expire<input type="date" name="assurance_expire_le" value="<?=e($v['assurance_expire_le']??'')?>"></label><label>Cadence vidange KM<input type="number" name="cadence_vidange" value="<?=e($v['cadence_vidange']??10000)?>"></label><label>KM dernière vidange<input type="number" name="km_derniere_vidange" value="<?=e($v['km_derniere_vidange']??0)?>"></label><label>Cadence courroie KM<input type="number" name="cadence_courroie" value="<?=e($v['cadence_courroie']??80000)?>"></label><label>KM dernière courroie<input type="number" name="km_derniere_courroie" value="<?=e($v['km_derniere_courroie']??0)?>"></label><label class="span2">Remarques<textarea name="remarques"><?=e($v['remarques']??'')?></textarea></label><div class="form-actions span2"><button class="btn primary">Enregistrer</button><a class="btn" href="/voitures.php">Annuler</a></div></form><?php endif; ?>
<div class="cards-grid"><?php foreach($rows as $v): ?><div class="car-card"><div class="car-top"><b><?=e($v['marque'].' '.$v['modele'])?></b><span class="badge <?=strtolower($v['statut'])?>"><?=e($v['statut'])?></span></div><div class="plate"><?=e($v['immatriculation'])?></div><p><?=e($v['type_vehicule'])?> · <?=e($v['carburant'])?> · <?=e($v['kilometrage_actuel'])?> km</p><strong><?=money($v['cout_jour'])?> / jour</strong><div class="actions"><?php if(can('voitures')):?><a class="btn small" href="/voitures.php?edit=<?=$v['id']?>">Modifier</a><a class="btn small danger" data-confirm="Supprimer ce véhicule ?" href="/voitures.php?delete=<?=$v['id']?>">Supprimer</a><?php endif;?></div></div><?php endforeach;?></div></section><?php render_footer(); ?>
